### ISSUE TITLE
How to use COLMAP with computed intrinsic parameters

### ISSUE THREAD

**Issue by sharan21** [alexvbogdan/DeepCalib#3]
Although this is not directly a part of functionalities in the repo, I need assistance replicating the 'undistortion' section using COLMAP that I have already installed. I went through the MATLAB code you have mentioned but want to avoid it because its not easily automatize using Matlab. Please excuse me if this seems like an inappropriate please to post the following question, I could not find any email to write this to:

1. Can you specify what CLI commands you are using with colmap to feed in the camera intrinsic parameters? (or provide a GUI explanation if possible)
2. I so far am able to obtain the focal length and distortion factor but am not able to apply this for colman SFM distortion, theres alot of documentation but it does not connect these 2 things easily.

Thanks

**Comment by alexvbogdan** [comment]
Sorry, but as you said it is not related to this repo, so I will close this issue.

**Comment by rameau-fr** [comment]
Dear Sharan,

It is not simple to use these parameters in Colmap since this framework does not propose the spherical model. In the DeepCalib paper, we have reimplemented a bundle adjustment for spherical camera using Ceres, in this case, COLMAP was exclusively used to determine the matches between views.

It might be possible to convert the unified spherical model's parameters into perspective/Brown but I do not think there is a direct formula for that purpose. A simple non-linear optimization would probably be a good approximation for such a conversion.

Best
