### ISSUE TITLE
Undistorted image size and distortion coefficients

### ISSUE THREAD

**Issue by lorenzodeveloper** [alexvbogdan/DeepCalib#7]
Hi,
How can I precisely calculate the output image (undistorted) size?
I saw that in your undistortion code you make the assumption that the output image will have a size that is 3 times larger than the input image (distorted) size (if I'm not wrong), but this is not always true: many times the real undistorted image has different size (lower or smaller).

I would also like to ask you if it is possible to convert the distortion parameter `xi` into a tuple of opencv Brown distortion coefficients `[k1, k2, p1, p2, k3]` to give to `cv2.undistort` function.
For example:
```python
[...]
dist_coeffs = get_coefficients_array_from(xi)
# Intrinsic matrix
K = np.array([[f_dist, 0, u0_dist], [0, f_dist, v0_dist], [0, 0, 1]])

h, w = distorted_image.shape[:2]

newcameramtx, roi = cv2.getOptimalNewCameraMatrix(K, dist_coeffs, (w, h), 1, (w, h))
im_undist = cv2.undistort(distorted_image, K, dist_coeffs, None, newcameramtx)
[...]
```
Thanks in advance.
Best,

Lorenzo

**Comment by alexvbogdan** [comment]
Hi Lorenzo, 

We did not calculate the output image size for a very simple reason: the part of the image that contains useful information will be skewed and will not be of rectangular shape. The corners will be sort of stretched outwards and there will be a black margin regardless of what you do. We made the output image 3 times bigger arbitrarily, just to see how much of the image we want to retain in order to minimize the black margin (you can remove it completely, by the way, by cropping a significant part of the image). The size of the black margin depends on the distortion parameter and will vary a lot.

I assume that you can convert `xi` to Brown coefficients with a certain error, but unfortunately, I can not tell you right away the method for doing so. 

I hope this answer is helpful.

**Comment by lorenzodeveloper** [comment]
Thank you for your reply.

I know, I was looking for a method that allow me to minimize the black margin directly from the projection, without having to crop the resulting image. (e.g. knowing the coordinates of the projected corners I can calculate the size of the output image based on that).

By the way, I will post here some code snippets if I will find a way to do what I asked to you.
Thanks again.

Best,

Lorenzo

P.S. I noticed a typo in my first post, I'm sorry about it (`lower or smaller` should have been => `bigger or smaller`).

**Comment by KOuldamer** [comment]
Hi  lorenzodeveloper
Did you succeed to converte  xi into a tuple of  distortion coefficients [k1, k2, p1, p2, k3]?

**Comment by lorenzodeveloper** [comment]
> Hi  lorenzodeveloper
> Did you succeed to converte  xi into a tuple of  distortion coefficients [k1, k2, p1, p2, k3]?
> 

Hi KOuldamer,
I'm sorry, but I did not succeed to converte the coefficient.
